### ISSUE TITLE
IPcam-combined - includes dark images?

### ISSUE THREAD

**Issue by coolguymatt** [MikeLud/CodeProject.AI-Custom-IPcam-Models#1]
Does IPcam-combined include the dark images as well? I am unsure.

**Comment by MikeLud** [comment]
> Does IPcam-combined include the dark images as well? I am unsure.

Not yet, I am going to update the models,. I do not have an ETA yet.

**Comment by MikeLud** [comment]
Closed

**Comment by cayossarian** [comment]
Good news but the model file shows it’s still the old one.  Do you need to push it to the repository?

**Comment by MikeLud** [comment]
I did not update the model yet.
